name: ✨ Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        We'd love to hear your ideas! Please describe the feature you'd like to see.

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of RealWorldClaw does this relate to?
      options:
        - Platform API
        - CLI (rwc)
        - Frontend / Dashboard
        - Printer Adapters
        - Orders / Maker Network
        - Hardware
        - Developer Experience
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is it related to a frustration?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or features you've considered?
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots.
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues and this is not a duplicate.
          required: true
        - label: I am willing to submit a PR for this feature.
          required: false
